"""
server/app.py
=============
FastAPI app for LexForge — created via openenv.core.create_fastapi_app().

Endpoints (auto-generated by create_fastapi_app):
  POST /reset   → LexObservation
  POST /step    → LexObservation
  GET  /state   → LexState
  GET  /health  → {"status": "ok"}

Extra endpoints added here:
  POST /upload  → triggers parser_agent OCR pipeline
  GET  /info    → environment metadata
"""

from __future__ import annotations
import sys, os
sys.path.insert(0, os.path.dirname(__file__))

from openenv.core import create_fastapi_app
from environment import LexForgeEnvironment

import importlib.util, pathlib

# ── Load models from parent package ──────────────────────────────────────────
def _load(name, rel):
    p    = pathlib.Path(__file__).parent.parent / rel
    spec = importlib.util.spec_from_file_location(name, p)
    mod  = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod

_models = _load("models", "models.py")
LexAction      = _models.LexAction
LexObservation = _models.LexObservation

# ── Core app (handles /reset, /step, /state, /health) ────────────────────────

def _api_clip(v):
    """Force reward strictly into (0.01, 0.99) at API boundary."""
    if v is None: return 0.5
    try:
        f = float(v)
        if f <= 0.0: return 0.01
        if f >= 1.0: return 0.99
        return round(max(0.01, min(0.99, f)), 4)
    except: return 0.5


app = create_fastapi_app(LexForgeEnvironment, LexAction, LexObservation)

# ── Reward clipping middleware ─────────────────────────────────────────────────
import json as _json
from starlette.middleware.base import BaseHTTPMiddleware
from starlette.responses import Response as _Response

class RewardClipMiddleware(BaseHTTPMiddleware):
    """Intercept /reset and /step responses, clip reward to (0.01, 0.99)."""
    async def dispatch(self, request, call_next):
        response = await call_next(request)
        if request.url.path in ("/reset", "/step"):
            body = b""
            async for chunk in response.body_iterator:
                body += chunk
            try:
                data = _json.loads(body)
                # Clip top-level reward
                if "reward" in data:
                    r = data["reward"]
                    if r is None:
                        data["reward"] = 0.5
                    else:
                        r = float(r)
                        data["reward"] = 0.01 if r <= 0.0 else (0.99 if r >= 1.0 else round(max(0.01, min(0.99, r)), 4))
                # Clip nested observation reward
                if "observation" in data and isinstance(data["observation"], dict):
                    obs = data["observation"]
                    if "reward" in obs:
                        r = obs["reward"]
                        if r is None:
                            obs["reward"] = 0.5
                        else:
                            r = float(r)
                            obs["reward"] = 0.01 if r <= 0.0 else (0.99 if r >= 1.0 else round(max(0.01, min(0.99, r)), 4))
                body = _json.dumps(data).encode()
            except Exception:
                pass
            return _Response(content=body, status_code=response.status_code,
                           headers=dict(response.headers), media_type="application/json")
        return response

app.add_middleware(RewardClipMiddleware)


# ── Extra endpoints ───────────────────────────────────────────────────────────
from fastapi import UploadFile, File, HTTPException
from fastapi.responses import JSONResponse
import tempfile, shutil

@app.post("/upload", summary="OCR a legal document via Sarvam OCR, inject clauses into next reset()")
async def upload_document(file: UploadFile = File(...)):
    """
    Accept a PDF or image file, run sarvamai/sarvam-ocr, return parsed clauses.
    Clauses are returned as JSON — pass them to /reset as injected_clauses.
    """
    allowed = {".pdf", ".png", ".jpg", ".jpeg", ".tiff", ".tif"}
    ext = os.path.splitext(file.filename or "")[-1].lower()
    if ext not in allowed:
        raise HTTPException(400, f"Unsupported file type: {ext}. Allowed: {allowed}")

    # Save upload to temp file
    with tempfile.NamedTemporaryFile(delete=False, suffix=ext) as tmp:
        shutil.copyfileobj(file.file, tmp)
        tmp_path = tmp.name

    try:
        # Import parser_agent (lazy — not required at startup)
        _pa = _load("parser_agent", "parser_agent.py")
        clauses = _pa.parse_document(tmp_path)
        return JSONResponse({"clauses": clauses, "count": len(clauses)})
    except Exception as e:
        raise HTTPException(500, f"OCR failed: {e}")
    finally:
        os.unlink(tmp_path)


@app.get("/info", summary="Environment metadata")
def get_info():
    from fixtures import TASK_CLAUSE_SETS, TASK_MAX_STEPS, TASK_DESCRIPTIONS, TASK_AVAILABLE_ACTIONS
    return {
        "name":        "LexForge",
        "version":     "1.0.0",
        "description": "Comprehensive Legal Intelligence Environment — 10 domains, 4 difficulty tiers",
        "tasks": {
            tid: {
                "description":       TASK_DESCRIPTIONS[tid],
                "clause_count":      len(TASK_CLAUSE_SETS[tid]),
                "max_steps":         TASK_MAX_STEPS[tid],
                "available_actions": TASK_AVAILABLE_ACTIONS[tid],
            }
            for tid in ["easy", "medium", "hard", "expert"]
        },
    }

def main():
    import uvicorn
    uvicorn.run("app:app", host="0.0.0.0", port=7860, workers=1)

if __name__ == "__main__":
    main()
