"""
server/app.py
=============
FastAPI app for LexForge — created via openenv.core.create_fastapi_app().

Endpoints (auto-generated by create_fastapi_app):
  POST /reset   → LexObservation
  POST /step    → LexObservation
  GET  /state   → LexState
  GET  /health  → {"status": "ok"}

Extra endpoints added here:
  POST /upload  → triggers parser_agent OCR pipeline
  GET  /info    → environment metadata
"""

from __future__ import annotations
import sys, os
sys.path.insert(0, os.path.dirname(__file__))

from openenv.core import create_fastapi_app
from environment import LexForgeEnvironment

import importlib.util, pathlib

# ── Load models from parent package ──────────────────────────────────────────
def _load(name, rel):
    p    = pathlib.Path(__file__).parent.parent / rel
    spec = importlib.util.spec_from_file_location(name, p)
    mod  = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod

_models = _load("models", "models.py")
LexAction      = _models.LexAction
LexObservation = _models.LexObservation

# ── Core app (handles /reset, /step, /state, /health) ────────────────────────
app = create_fastapi_app(LexForgeEnvironment, LexAction, LexObservation)

# ── Extra endpoints ───────────────────────────────────────────────────────────
from fastapi import UploadFile, File, HTTPException
from fastapi.responses import JSONResponse
import tempfile, shutil

@app.post("/upload", summary="OCR a legal document via Sarvam OCR, inject clauses into next reset()")
async def upload_document(file: UploadFile = File(...)):
    """
    Accept a PDF or image file, run sarvamai/sarvam-ocr, return parsed clauses.
    Clauses are returned as JSON — pass them to /reset as injected_clauses.
    """
    allowed = {".pdf", ".png", ".jpg", ".jpeg", ".tiff", ".tif"}
    ext = os.path.splitext(file.filename or "")[-1].lower()
    if ext not in allowed:
        raise HTTPException(400, f"Unsupported file type: {ext}. Allowed: {allowed}")

    # Save upload to temp file
    with tempfile.NamedTemporaryFile(delete=False, suffix=ext) as tmp:
        shutil.copyfileobj(file.file, tmp)
        tmp_path = tmp.name

    try:
        # Import parser_agent (lazy — not required at startup)
        _pa = _load("parser_agent", "parser_agent.py")
        clauses = _pa.parse_document(tmp_path)
        return JSONResponse({"clauses": clauses, "count": len(clauses)})
    except Exception as e:
        raise HTTPException(500, f"OCR failed: {e}")
    finally:
        os.unlink(tmp_path)


@app.get("/info", summary="Environment metadata")
def get_info():
    from fixtures import TASK_CLAUSE_SETS, TASK_MAX_STEPS, TASK_DESCRIPTIONS, TASK_AVAILABLE_ACTIONS
    return {
        "name":        "LexForge",
        "version":     "1.0.0",
        "description": "Comprehensive Legal Intelligence Environment — 10 domains, 4 difficulty tiers",
        "tasks": {
            tid: {
                "description":       TASK_DESCRIPTIONS[tid],
                "clause_count":      len(TASK_CLAUSE_SETS[tid]),
                "max_steps":         TASK_MAX_STEPS[tid],
                "available_actions": TASK_AVAILABLE_ACTIONS[tid],
            }
            for tid in ["easy", "medium", "hard", "expert"]
        },
    }

def main():
    import uvicorn
    uvicorn.run("app:app", host="0.0.0.0", port=7860, workers=1)

if __name__ == "__main__":
    main()
